package Protocol;

import cyy_IM_protocol.Cyy_factory;
import cyy_IM_protocol.IM_Handler;
import cyy_IM_protocol.IM_capsulation;
import org.junit.Test;

import java.io.UnsupportedEncodingException;

public class protocolFactory_test {
    String testpacket = "CYY 0.1\r\n"
            +"CYYClient 1.0\r\n"
            +"GnuPG 2.0\r\n"
            +"-1\r\n"
            +"12345566\r\n"
            + IM_Handler.ACTION_contactInitializing+"\r\n"
            +"IMAP\r\n"
            +"11\r\n"
            +"mac@mail.sustc.edu.cn\r\n"
            +"0\r\n"
            +"b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9\r\n"
            +"luoyq@mail.sustc.edu.cn\r\n"
            +"\r\n"
            +"hello world\r\n"
            +"\r\n"
            +"\r\n";
    String testpacket_group = "CYY 0.1\r\n"
            +"CYYClient 1.0\r\n"
            +"GnuPG 2.0\r\n"
            +"-1\r\n"
            +"12345566\r\n"
            + IM_Handler.ACTION_contactInitializing+"\r\n"
            +"IMAP\r\n"
            +"11\r\n"
            +"mac@mail.sustc.edu.cn\r\n"
            +"1\r\n"
            +"b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9\r\n"
            +"luoyq@mail.sustc.edu.cn;\r\n"
            +"1\r\n"
            +"\r\n"
            +"hello world\r\n"
            +"\r\n"
            +"\r\n";
    String generate = "";
    String decoded = "";
    public String test_gen(boolean Individual_flag) throws UnsupportedEncodingException {
        Cyy_factory f = Cyy_factory.get_cyyfactory();
        f.create_messageObj("hello world", "GnuPG 2.0", -1, 12345566, 12);
        String[] dests = {"luoyq@mail.sustc.edu.cn"};
        if(Individual_flag){
            IM_capsulation cap = f.capsulate("CYYClient 1.0",IM_Handler.ACTION_contactInitializing, "IMAP",
                    "mac@mail.sustc.edu.cn","luoyq@mail.sustc.edu.cn");
            return new String(f.packet_generate(cap),"UTF-8");
        }else{
            IM_capsulation cap = f.capsulate("CYYClient 1.0",IM_Handler.ACTION_contactInitializing, "IMAP",
                    "mac@mail.sustc.edu.cn",dests, 1);
            return new String(f.packet_generate(cap),"UTF-8");
        }

    }

    @Test
    public void test_packet_gen_individual(){


        try {
            generate = test_gen(true);
            assert(generate.equals(testpacket));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }


    }
    @Test
    public void test_packet_parse_individual() throws UnsupportedEncodingException {
        String gen = test_gen(true);// this is the string generated by sender side
        Cyy_factory f = Cyy_factory.get_cyyfactory();

        IM_capsulation cap = f.packet_parse(gen);//this is parsed by receiver side
        //then let's generate it again to see whether the parsed one is same with our original generating target, test packet
        String re_gen = new String(f.packet_generate(cap),"UTF-8");
        assert(re_gen.equals(testpacket));
    }
    @Test
    public void test_packet_gen_group(){
        try {
            generate = test_gen(false);
            assert(generate.equals(testpacket_group));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

    }
    @Test
    public void test_packet_parse_group() throws UnsupportedEncodingException {
        String gen = test_gen(false);// this is the string generated by sender side
        Cyy_factory f = Cyy_factory.get_cyyfactory();
        IM_capsulation cap = f.packet_parse(gen);//this is parsed by receiver side
        //then let's generate it again to see whether the parsed one is same with our original generating target, test packet
        String re_gen = new String(f.packet_generate(cap),"UTF-8");
        assert(re_gen.equals(testpacket_group));
    }
}
