package cyy_IM_protocol;

import javax.mail.*;

public interface Cyy_factory {
    // first step create message_cyy

    /**
     * @param raw_text        String: the original content for sending
     * @param Encryption_type String: the type of encryption
     * @param Sequence_number integer: the sequence number generated by a certain session for each sending
     * @param timeStamp       long: the timestamp when the message is generated
     * @param session_id      int: the id of session that this message belong to
     * @return Message_cyy for upper layer
     */
    Message_cyy create_messageObj(String raw_text, String Encryption_type, int Sequence_number, long timeStamp, int session_id);
    //second step prepare for sending

    /**
     * @param UserAgent       String: the client edition
     * @param ACTION_type     String: the action description: could be found in static resources in  IM_Handler of cyy_IM_protocol package
     * @param mail_protocol   String: mail protocol description: determined by user no influence on usage of this method
     * @param source          String: the email address of sender
     * @param Destination     String[]: the email address list of recipients
     * @param group_id        int: the group id that initiated by the organiser
     * @return IM_capsulation object of IM_packet
     */
    IM_capsulation capsulate(String UserAgent, String ACTION_type, String mail_protocol, String source, String[] Destination, int group_id);

    /**
     *overloading with no group_id parameter
     */
    IM_capsulation capsulate(String UserAgent, String ACTION_type, String mail_protocol, String source, String Destination);

    /**
     *
     * @param packet_obj    the IM_capsulation object
     * @return the packet in string with encrypted content
     */
    byte[] packet_generate(IM_capsulation packet_obj);

    /**
     *
     * @param raw_packet the original packet coming from internet
     * @return
     */
    IM_capsulation packet_parse(String raw_packet);
}
